<?php

/*
|--------------------------------------------------------------------------
| Permissions par défaut par rôle
|--------------------------------------------------------------------------
|
| Les rôles ne donnent PAS automatiquement de permissions (voir RoleSeeder :
| aucune permission n'est attachée aux rôles). Chaque utilisateur reçoit ses
| permissions individuellement. Ce tableau sert uniquement de MODÈLE : à la
| création d'un utilisateur, on lui attribue directement les permissions
| listées ici pour son rôle. L'administrateur peut ensuite les ajuster une
| par une via « Assigner permissions ». Les autorisations réelles de
| l'application (sidebar, boutons, routes) ne dépendent QUE des permissions
| directes de l'utilisateur.
|
| Le rôle « superadmin » n'apparaît pas ici : il contourne toutes les
| vérifications via Gate::before (voir AppServiceProvider).
|
*/

return [
    'directeur_general' => [
        'utilisateurs.voir',
        'utilisateurs.creer',
        'utilisateurs.modifier',
        'utilisateurs.desactiver',
        'roles.gerer',
        'chauffeurs.voir',
        'chauffeurs.creer',
        'chauffeurs.modifier',
        'chauffeurs.supprimer',
        'vehicules.voir',
        'vehicules.creer',
        'vehicules.modifier',
        'vehicules.supprimer',
        'affectations.voir',
        'affectations.creer',
        'affectations.modifier',
        'affectations.terminer',
        'recettes.voir',
        'recettes.creer',
        'recettes.modifier',
        'recettes.supprimer',
        'absences.voir',
        'absences.creer',
        'absences.modifier',
        'absences.valider',
        'absences.supprimer',
        'depenses.voir',
        'depenses.creer',
        'depenses.modifier',
        'depenses.supprimer',
        'accidents.voir',
        'accidents.creer',
        'accidents.modifier',
        'accidents.supprimer',
        'incidents.voir',
        'incidents.creer',
        'incidents.modifier',
        'incidents.supprimer',
        'caisse.voir',
        'caisse.ouvrir',
        'caisse.fermer',
        'caisse.mouvementer',
        'finances.voir',
        'rapports.voir',
        'personnel.voir',
        'personnel.creer',
        'personnel.modifier',
        'personnel.supprimer',
        'bulletins.voir',
        'bulletins.gerer',
        'mandats.voir',
        'mandats.gerer',
        'mandats.signer',
        'validations.voir',
    ],

    'responsable_parc' => [
        'chauffeurs.voir',
        'chauffeurs.creer',
        'chauffeurs.modifier',
        'chauffeurs.supprimer',
        'vehicules.voir',
        'vehicules.creer',
        'vehicules.modifier',
        'vehicules.supprimer',
        'affectations.voir',
        'affectations.creer',
        'affectations.modifier',
        'affectations.terminer',
        'recettes.voir',
        'absences.voir',
        'absences.creer',
        'absences.modifier',
        'depenses.voir',
        'depenses.creer',
        'depenses.modifier',
        'accidents.voir',
        'accidents.creer',
        'accidents.modifier',
        'incidents.voir',
        'incidents.creer',
        'incidents.modifier',
    ],

    'gestionnaire' => [
        'chauffeurs.voir',
        'chauffeurs.creer',
        'chauffeurs.modifier',
        'vehicules.voir',
        'vehicules.creer',
        'vehicules.modifier',
        'affectations.voir',
        'affectations.creer',
        'affectations.modifier',
        'affectations.terminer',
        'recettes.voir',
        'recettes.creer',
        'recettes.modifier',
        'absences.voir',
        'absences.creer',
        'absences.modifier',
        'depenses.voir',
        'depenses.creer',
        'depenses.modifier',
        'accidents.voir',
        'accidents.creer',
        'accidents.modifier',
        'incidents.voir',
        'incidents.creer',
        'incidents.modifier',
        'caisse.voir',
        'finances.voir',
        'rapports.voir',
        'personnel.voir',
        'personnel.creer',
        'personnel.modifier',
        'bulletins.voir',
        'mandats.voir',
    ],

    'comptable' => [
        'chauffeurs.voir',
        'vehicules.voir',
        'affectations.voir',
        'recettes.voir',
        'recettes.creer',
        'recettes.modifier',
        'absences.voir',
        'depenses.voir',
        'depenses.creer',
        'depenses.modifier',
        'accidents.voir',
        'incidents.voir',
        'caisse.voir',
        'finances.voir',
        'rapports.voir',
        'personnel.voir',
        'bulletins.voir',
        'bulletins.gerer',
        'mandats.voir',
        'mandats.gerer',
    ],

    'caissier' => [
        'chauffeurs.voir',
        'vehicules.voir',
        'affectations.voir',
        'recettes.voir',
        'recettes.creer',
        'recettes.modifier',
        'absences.voir',
        'depenses.voir',
        'depenses.creer',
        'accidents.voir',
        'incidents.voir',
        'caisse.voir',
        'caisse.ouvrir',
        'caisse.fermer',
        'caisse.mouvementer',
    ],
];
